spring:
  application:
    name: customer-portal
  datasource:
    url: jdbc:h2:file:./data/customer-portal;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
