-- US-001 Customer Registration — authoritative schema.
-- Source: docs/designs/database/US-001-db-design.md §8.1 (hand-maintained per
-- persistence-conventions.md PC-2 / security-conventions.md SC-8). The Customer
-- entity mapping must agree with this file exactly (ddl-auto=validate).

CREATE TABLE IF NOT EXISTS customer (
    id            BIGINT                   GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(254)             NOT NULL,
    password_hash VARCHAR(60)              NOT NULL,
    role          VARCHAR(20)              NOT NULL DEFAULT 'CUSTOMER',
    enabled       BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_customer       PRIMARY KEY (id),
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT ck_customer_role  CHECK (role IN ('CUSTOMER', 'ADMIN'))
);
